routes/web.php
<?php

Route::middleware(['auth'])->group(function () {
    Route::post('/image/{student}', 'StudentController@upload')->name('image.upload');
    Route::get('/list/{group}', 'GroupController@viewStudents')->name('view.students');
    Route::get('/main', 'MainController@index')->name('main.index');
    Route::resource('students', 'StudentController');
    Route::resource('groups', 'GroupController');
});

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

app/Models/Student.php
<?php

namespace App\Models;

use App\Models\Group;
use App\Models\Student;
use App\Models\Rating;
use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    protected $fillable = [
        'group_id',
        'name',
        'birthday'
    ];

    public function group()
    {
        return $this->belongsTo(Group::class);
    }

    public function ratings()
    {
        return $this->hasMany(Rating::class);
    }

    public function colorHightlight($value)
    {
        $active =" ";
        if ($value == 5.0) {
            $active = "style = color:green;";
        } elseif ($value <= 3.9) {
            $active = "style = color:red;";
        } elseif ($value >= 4.0 && $value < 5.0) {
            $active = "style = color:#FFE4B5;";
        }
        return $active;
    }

    public function StudentPerformance($student, $max, $subjCount)
    {
        $maxpoint = $max * $subjCount;
        if ($maxpoint != null) {
            $result = round(($student->ratings->sum('points') / ($max * $subjCount)) * 100, 2);
            return $result;
        } else {
            return 0;
        }
    }
    public function performanceInSubjAsPercent($point, $maxpoint)
    {
        return round(($point / $maxpoint) * 100, 2);
    }

    public function scopeFilter ($builder, $filters)
    {
        return $filters->apply($builder);
    }

}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use Storage;
use App\Filter;
use App\Models\Group;
use App\Models\Rating;
use App\Models\Subject;
use App\Models\Student;
use Illuminate\Http\Request;
use App\Http\Requests\StudentRequests\StudentCreateRequest;
use App\Http\Requests\StudentRequests\StudentEditRequest;
use App\Http\Requests\StudentRequests\StudentImageRequest;

class StudentController extends Controller
{
    public function index(Request $request, Filter $filters)
    {
        $subjCount = Subject::count();
        //$groups = Group::all();

        $students = Student::with('ratings', 'group')
            ->filter($filters)
            ->paginate(3)
        ->appends(
            $request->only(['fio','birt', 'group', 'russtud', 'mathstud', 'histstud', 'studsort']));
        return view('students.index', compact('students', 'subjCount'));
    }

    public function create(Request $request)
    {
        $groups = Group::all();
        $student = new Student;

        $this->authorize('show', $student);
        return view('students.create', compact('groups'));
    }

    public function store(StudentCreateRequest $request)
    {
        $student = Student::create($request->all());
        Rating::create(['points' => $request->input('rating-rus'), 'student_id' => $student->id]);
        Rating::create(['points' => $request->input('rating-math'), 'student_id' => $student->id]);
        Rating::create(['points' => $request->input('rating-hist'), 'student_id' => $student->id]);
        return redirect('/students');
    }

    public function show(Student $student, Request $request)
    {
        $groups = Group::all();

        $this->authorize('show', $student);
        return view('students.show', compact('student', 'groups'));
    }

    public function edit(Student $student, StudentEditRequest $request)
    {
        $student->update($request->all());
        return redirect(route('students.index'));
    }

    public function destroy(Student $student, Request $request)
    {
        $this->authorize('delete', $student);
        if ($student->imgpath != null) {
            Storage::disk('public')->delete($student->imgpath);
        }
        $student->delete();
        return back();
    }

    public function upload(Student $student, StudentImageRequest $request)
    {
        if ($student->imgpath != null) {
            Storage::disk('public')->delete($student->imgpath);
        }
        $groups = Group::all();
        $path = $request->file('image')->store('uploads', 'public');

        $student->imgpath = $path;
        $student->save();
        return back();
    }
}

resources/views/students/create.blade.php
@extends ('includes._layout')

@section ('content')
	<form action = "{{ route ('students.store') }}" method = "POST">
		 {{ csrf_field() }}
		<div style="width: 300px">
		  	<div class="input-group-prepend">
		  		<span class="input-group-text">Добавить студента</span>
		  	</div>
		 	<input type="text" aria-label="ФИО студента" class="form-control" placeholder="ФИО студента" name="name">
		  	<input type="date" aria-label="Дата рождения" class="form-control" placeholder="Введите дату рождения" name="birthday">
		  	<div>
			  	<select class="custom-select" id="inputGroupSelect01" name="group_id">
			  		<option disabled selected>Выберите группу</option>
				@foreach ($groups as $group)
					<option value="{{$group->id}}"> {{$group->title}} </option>
				@endforeach
				</select>
			</div>
		  	<input type="text" aria-label="Оценка по русскому языку" class="form-control" placeholder="Укажите оценку по русскому языку" name="rating-rus" required>
		  	<input type="text" aria-label="Оценка по математике" class="form-control" placeholder="Укажите оценку по математике" name="rating-math" required>
		  	<input type="text" aria-label="Оценка по истории" class="form-control" placeholder="Укажите оценку по истории" name="rating-hist" required>
		  	<div>
		  		<button class="btn btn-outline-success" type="submit">Добавить</button>
		  	</div>
		</div>
	</form>
@endsection

resources/views/students/index.blade.php
@extends ('includes._layout')

@section ('filter')
	@include ('includes.filters.studentfilter')
@endsection
@php
    use App\Models\Student;
@endphp

@section ('content')
	<table class="table table-sm">
	<thead>
		<th>Полное имя</th>
		<th>Дата рождения</th>
		<th>Группа</th>
		<th>Успеваемость</th>
		<th>Усп. по русскому языку</th>
		<th>Усп. по математике</th>
		<th>Усп. по истории</th>
	</thead>
	<tbody>
	@include('includes.filters.studentsort')
	@foreach ($students as $student)
		{{dd($student->group)}}
		<tr>
			<td><div class="body">&nbsp; {{ $student->name }} </div></td>
			<td><div class="body">&nbsp; {{ $student->birthday }} </div></td>
			<td><div class="body">&nbsp; {{ $student->groups }} </div></td>
			<td><div class="body">&nbsp;<b> {{ $student->StudentPerformance($student, 5, $subjCount) }}% </b></div></td>
			@foreach ($student->ratings as $rating)
				<td><div class="body"> {{$student->performanceInSubjAsPercent($rating->points, 5)}}% </div></td>
			@endforeach

			@can('show', $student)
				<td>
					<form action = "{{ route ('students.show', $student) }}" method = "GET">
					  {{ csrf_field() }}
					  <button type="submit" class="btn btn-primary">
						<i class="fa fa-trash"> Анкета </i>
					  </button>
					</form>
				</td>
			@endcan
			@can('delete', $student)
				<td>
					<form action="{{ route('students.destroy', $student) }}" method="post">
						@csrf
						@method('delete')
						<button type="submit" class="btn btn-danger">
						<i class="fa fa-trash"> Удалить </i>
					  </button>
					</form>
				</td>
			@endcan
		</tr>
	@endforeach
	</tbody>
	</table>

	<nav>
		<ul class="pagination">
			<div class="container" style="margin:0 30% 0 30%;;">{{$students->links()}}</div>
		</ul>
	</nav>

	@can('create', Student::class)
		<form action = "{{ route ('students.create') }}" method = "GET">
			@csrf
		   <div style="width: 300px">
				 <div class="input-group-prepend"><span class="input-group-text">Добавить студента</span>
				 <button class="btn btn-outline-success" type="submit">+</button></div>
		   </div>
	   </form>
	@endcan
@endsection

resources/views/students/show.blade.php
@extends ('includes._layout')

@section ('content')
  <div class="card-deck">
  <div class="card col-3" >
    <div class="card-body">
      <h5 class="card-title">Фото</h5>
        @include ('students.upload')
    </div>
  </div>
  <div class="card col-5">
    <div class="card-body">
      <h5 class="card-title">Анкета студента</h5>
      <form action = "{{ route ('students.edit', $student) }}" method = "GET">
          <div>
            <div>
              <label for="disabledTextInput">ФИО</label>
              <input type="text" value="{{$student->name}}" placeholder="{{$student->name}}" name="name" style="width: 260px">
            </div>
            <div>
              <label for="disabledTextInput">Дата рождения</label>
              <input type="date" value="{{$student->birthday}}" placeholder="{{$student->birthday}}" name="birthday">
            </div>
            <div>
              <label for="disabledTextInput">Группа</label>
            <div>
              <select required class="custom-select" name="group_id" style="width: 300px">
                 @foreach ($groups as $group)
                 <option value="{{$group->id}}"> {{$group->title}} </option>
                 @endforeach
              </select>
            </div>
            <div>
              <label for="disabledTextInput">Оценки</label>
              <input type="text" value="{{$student->ratings->pluck('points')}}" name="points" disabled="true">
            </div>
          </div>
          <div class="input-group-prepend">
            <span class="input-group-text">Принять изменения</span>
            <button class="btn btn-outline-info" type="submit">~</button>
          </div>
        </form>
    </div>
  </div>
</div>
@endsection

resources/views/students/upload.blade.php
@isset($student->imgpath)
	<div class="card" style="width: 10rem;">
  		<img class="card-img-top" src="{{ asset('/storage/'.$student->imgpath) }}">
	</div>
@endisset
<table>
	<tbody>
		<tr>
	        <td>
	          <form action="{{ route('image.upload', $student) }}" method="post" enctype="multipart/form-data">
	            {{ csrf_field() }}
	            <div class="input-group">
				  <div class="custom-file">
				    <input type="file" class="custom-file-input" id="inputGroupFile04" aria-describedby="inputGroupFileAddon04" name="image">
				    <label class="custom-file-label" for="inputGroupFile04">🔍</label>
				  </div>
				  <div class="input-group-append">
				    <button class="btn btn-outline-secondary" type="submit" id="inputGroupFileAddon04">🡒</button>
				  </div>
				</div>
	          </form>
	        </td>
	    </tr>
	</tbody>
</table>