routes/web.php
<?php

Route::middleware(['auth'])->group(function () {
    Route::post('/image/{student}', 'StudentController@upload')->name('image.upload');
    Route::get('/list/{group}', 'GroupController@viewStudents')->name('view.students');
    Route::get('/main', 'MainController@index')->name('main.index');
    Route::resource('students', 'StudentController');
    Route::resource('groups', 'GroupController');
});

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

app/Models/Group.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Group extends Model
{
    protected $fillable  = [
        'title',
        'description'
    ];

    public $avg;

    public function students()
    {
        return $this->hasMany(Student::class);
    }

    public function ratings()
    {
        return $this->hasManyThrough(Rating::class, Student::class);
    }

    public function avgRatingInGroup($mode)
    {
        $this->avg = array();
        foreach ($this->students as $student) {
            $this->avg[]=$student->ratings->get($mode)->points;
        }
        $count = count($this->avg);
        $sum = array_sum($this->avg);
        if ($count != null) {
            switch ($mode) {
                case '0':
                    $this->avgrus = $sum / $count;
                    $this->save();
                    break;
                case '1':
                    $this->avgmath = $sum / $count;
                    $this->save();
                    break;
                case '2':
                    $this->avghist = $sum / $count;
                    $this->save();
                    break;
            }
        }
        if ($count != null) {
            return $sum / $count;
        } else {
            return 0;
        }
    }

    public function groupPerformance($max, $subjCount)
    {
        $studCount = $this->students->count();
        $maxpoint = $max * $studCount * $subjCount;
        if ($maxpoint != null) {
            return round(($this->ratings->sum('points') / $maxpoint) * 100, 2);
        } else {
            return 0;
        }
    }

    public function scopeFilter($builder, $filters)
    {
        return $filters->apply($builder);
    }
}

app/Http/Controllers/GroupController.php
<?php

namespace App\Http\Controllers;

use App\Filter;
use App\Models\Group;
use App\Models\Subject;
use Illuminate\Http\Request;
use App\Http\Requests\GroupRequests\GroupCreateRequest;
use App\Http\Requests\GroupRequests\GroupEditRequest;

class GroupController extends Controller
{

    public function index(Request $request, Filter $filters)
    {
        $subjCount = Subject::count();
        $groups = Group::with('students.ratings')
            ->filter($filters)
            ->with('ratings')
            ->paginate(3)
        ->appends(
            $request->only(['title', 'desk', 'rus', 'math', 'hist', 'sort']));
        return view('groups.index', compact('groups', 'subjCount'));
    }

    public function create(Request $request)
    {
        $group = new Group;
        $this->authorize('create', $group);
        return view('groups.create');
    }

    public function store(GroupCreateRequest $request)
    {
        Group::create($request->all());
        return redirect(route('groups.index'));
    }

    public function show(Group $group, Request $request)
    {
        $this->authorize('show', $group);
        return view('groups.show', compact('group'));
    }

    public function edit(Group $group, GroupEditRequest $request)
    {
        $group->update($request->all());
        return redirect(route('groups.index'));
    }

    public function destroy(Group $group, Request $request)
    {
        $this->authorize('delete', $group);
            foreach ($group->students as $student) {
                if ($student->imgpath != null) {
                    Storage::disk('public')->delete($student->imgpath);
                }
                $student->delete;
            }
        $group->delete();
        return back();
    }

    public function viewStudents(Group $group)
    {
        return view('groups.studlist', compact('group'));
    }
}

resources/views/groups/create.blade.php
@extends ('includes._layout')

@section ('content')
	<form action = "{{ route ('groups.store') }}" method = "POST">
	 	@csrf
	  	<div class="input-group-prepend">
	    	<span class="input-group-text">Добавление группы</span>
	  	</div>
	  	<div style="width: 300px">
	 		<input type="text" aria-label="Название группы" class="form-control" placeholder="Введите название группы" name='title'>
	  		<input type="text" aria-label="Описание группы" class="form-control" placeholder="Введите описание группы" name="description">
	  		<div><button class="btn btn-outline-success" type="submit">Добавить</button></div>
	  	</div>
	</form>
@endsection

resources/views/groups/index.blade.php
@extends ('includes._layout')

@section ('filter')
	@include ('includes.filters.groupfilter')
@endsection
@php
    use App\Models\Group;
@endphp

@section ('content')

<table class="table table-sm">
<thead>
	<th>Название группы</th>
	<th>Описание</th>
	<th>Успеваемость</th>
	<th>Средняя оценка по русскому языку</th>
	<th>Средняя оценка по математике</th>
	<th>Cредняя оценка по истории</th>
	<th></th>
</thead>
<tbody>
	@include('includes.filters.groupsort')
	<tr>
		@foreach ($groups as $group)
			<tr>
				<td><div class="body">&nbsp;<b> {{ $group->title }} </b></div></td>
				<td><div class="body">&nbsp;<b> {{ $group->description }} </b></div></td>
				<td><div class="body">&nbsp;<b> {{ $group->groupPerformance(5, $subjCount) }}% </b></div></td>
				@for ($i = 0; $i < $subjCount; $i++)
					<td><i>{{round($group->avgRatingInGroup($i), 2)}}</i></td>
				@endfor

				@can('show', $group)
					<td>
						<form action = "{{ route ('groups.show', $group) }}" method = "GET">
							@csrf
							<button type="submit" class="btn btn-primary">
								<i class="fa fa-trash"> Редактировать </i>
							</button>
						</form>
					</td>
				@endcan
				@can('delete', $group)
					<td>
						<form action="{{ route('groups.destroy', ['id' => $group->id]) }}" method="post">
							@csrf
							@method('delete')
							<button type="submit" class="btn btn-danger">
								<i class="fa fa-trash"> Удалить</i>
							</button>
						</form>
					</td>
				@endcan
				<td>
					<form action="{{ route('view.students', $group) }}" method="get">
						@csrf
					    <button type="submit" class="btn btn-outline-dark">
					    	🚻
				      </button>
				    </form>
				</td>
			</tr>
		@endforeach
</tbody>
</table>

<nav>
	<ul class="pagination">
		<div class="container" style="margin:0 30% 0 30%;;">{{$groups->links()}}</div>
	</ul>
</nav>

@can('create', Group::class)
	<form action = "{{ route ('groups.create') }}" method = "GET">
			{{ csrf_field() }}
		<div style="width: 300px">
			<div class="input-group-prepend"><span class="input-group-text">Добавить группу</span>
			<button class="btn btn-outline-success" type="submit">+</button></div>
		</div>
	</form>
@endcan

@endsection

resources/views/groups/show.blade.php
@extends ('includes._layout')

@section ('content')
<table class="table table-bordered">
    <thead>
      <tr>
        <th scope="col" width="">Данные группы</th>
      </tr>
    </thead>
    <tbody>
      <tr  width="120">
        <form action = "{{ route ('groups.edit', $group) }}" method = "GET">
          <td width="400">
            <div>
              <div>
                <label for="disabledTextInput">Название группы</label>
                <input type="text" value="{{$group->title}}" placeholder="{{$group->title}}" name="title">
              </div>
              <div>
                <label for="disabledTextInput">Описание группы</label>
                <input type="text" value="{{$group->description}}" placeholder="{{$group->description}}" name="description">
              </div>
              <div>
                <label for="disabledTextInput">Кол-во студентов</label>
                <input type="text" value="{{$group->students->count()}}" name="studcount" disabled="true">
            </div>
            <div class="input-group-prepend">
              <span class="input-group-text">Принять изменения</span>
              <button class="btn btn-outline-info" type="submit">~</button></div>
            </div>
          </td>
        </form>
      </tr>
    </tbody>
</table>
@endsection

resources/views/groups/studlist.blade.php
@extends ('includes._layout')

@section ('content')
	<table class="table table-hover">
		<thead>
			<th>№ п\п</th>
			<th>Имя</th>
			<th>Дата рождения</th>
		</thead>
		<tbody>
			<tr>
				@foreach ($group->students as $student)
					<tr>
						<td>{{$loop->index+1}}</td>
						<td>{{$student->name}}</td>
						<td>{{$student->birthday}}</td>
					</tr>
				@endforeach
			</tr>
		</tbody>
	</table>
@endsection